{
 "title": "AI RCA System",
 "panels": [
  {
   "title": "Application Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"flask-app\"}"
    }
   ]
  },
  {
   "title": "Errors Only",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"flask-app\"} |= \"ERROR\""
    }
   ]
  },
  {
   "title": "Total HTTP Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 16 },
   "targets": [
    { "expr": "http_requests_total" }
   ]
  },
  {
   "title": "Total Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 16 },
   "targets": [
    { "expr": "app_errors_total" }
   ]
  }
 ]
}