name: PR Check

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  check-pr-description:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR has description
        if: github.event.pull_request.body == ''
        run: |
          echo 'PR description is empty. Please add a description.'
          exit 1
